Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,47 +1,66 @@
-name: test
-on: [push, workflow_dispatch]
+name: wokwi_test
+# either manually started, or on a schedule
+on: [ push, workflow_dispatch ]
 jobs:
-  test:
-    runs-on: ubuntu-24.04
+  wokwi_test:
+    # ubuntu
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+    # need the repo checked out
+    - name: checkout repo
+      uses: actions/checkout@v3
+      with:
+        submodules: recursive
 
-      - name: Install iverilog
-        shell: bash
-        run: sudo apt-get update && sudo apt-get install -y iverilog
+    # install oss fpga tools
+    - name: install oss-cad-suite
+      uses: YosysHQ/setup-oss-cad-suite@v2
+      with:
+          python-override: true
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+    - run: | 
+        yosys --version
+        iverilog -V
+        cocotb-config --libpython
+        cocotb-config --python-bin
 
-      # Set Python up and install cocotb
-      - name: Setup python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
+    - name: checkout tt tools repo
+      uses: actions/checkout@v3
+      with:
+        repository: tinytapeout/tt-support-tools
+        path: tt
+        ref: tt03p5
 
-      - name: Install Python packages
-        shell: bash
-        run: pip install -r test/requirements.txt
+    # need python and requirements
+    - name: setup python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.10'
+    - run: pip install -r tt/requirements.txt
 
-      - name: Run tests
-        run: |
-          cd test
-          make clean
-          make
-          # make will return success even if the test fails, so check for failure in the results.xml
-          ! grep failure results.xml
+    # fetch the truth table
+    - name: fetch Verilog and build config
+      run: ./tt/tt_tool.py --create-user-config
 
-      - name: Test Summary
-        uses: test-summary/action@v2.3
-        with:
-          paths: "test/results.xml"
-        if: always()
+    # does the wokwi project have a truthtable?
+    - name: Check the truthtable exists
+      id: check_files
+      uses: andstor/file-existence-action@v2
+      with:
+        files: "src/truthtable.md"
 
-      - name: upload vcd
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
+    - name: test
+      if: steps.check_files.outputs.files_exists == 'true'
+      run: |
+        cd src
+        make clean
+        make
+        # make will return success even if the test fails, so check for failure in the results.xml
+        ! grep failure results.xml
+
+    - name: upload vcd
+      if: success() || failure()
+      uses: actions/upload-artifact@v3
+      with:
           name: test-vcd
-          path: |
-            test/tb.vcd
-            test/results.xml
+          path: src/*.vcd
